### ISSUE TITLE
Unable to run docker command

### ISSUE THREAD

**Issue by FireAstrox** [yeSpud/CS-372-Project#39]
After following the steps for cloning and running pnpm as well as adding the env file the docker command does not work, docker is not a recognized command

This was the step "Start the docker container by running docker compose up -d in the root project directory."

**Comment by yeSpud** [comment]
Do you have docker installed?

**Comment by FireAstrox** [comment]
No, as Prof Das specified the documentation needs to be step by step and makes no assumptions of installed services and includes any necessary references. Any issues that we encounter are raised and resolved only in GitHub to have a living history

**Comment by yeSpud** [comment]
Please install docker
https://docs.docker.com/engine/install/

I will also add a note in the readme to make it less ambiguous
