### ISSUE TITLE
Docker compose command not working

### ISSUE THREAD

**Issue by FireAstrox** [yeSpud/CS-372-Project#51]
When running the docker compose up -d command in the root directory of the project this error is given. This is after a fresh install of docker on Ubuntu 24

`WARN[0000] /home/rylan/CS-372-Project/docker-compose.yml: `version` is obsolete 
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Dcs-372-project%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied`

**Comment by yeSpud** [comment]
Is your user part of the docker group?

**Comment by FireAstrox** [comment]
Im not even sure what or where that is. Its not listed anywhere in the project documentation or docker documentation. I was able to start the service fine and run sudo docker run hello-world fine.

**Comment by yeSpud** [comment]
You shouldnt need to use sudo with docker once its started if youre part of the docker group

Try
```sh
sudo groupadd docker
sudo usermod -aG docker $USER
```
then restart your VM and try running `docker run hello-world` without sudo

~~this is part of the docker documentation: https://docs.docker.com/engine/install/linux-postinstall/~~

**Comment by yeSpud** [comment]
Running everything with sudo is super bad practice as it runs everything with the highest level of permission.

Im glad you got it working in the end though

**Comment by FireAstrox** [comment]
If you are trying to avoid using sudo then the group change should be added into the documentation as most users including myself will find that as an easier work around
