### ISSUE TITLE
Video URL input unclear - leads to unplayable videos

### ISSUE THREAD

**Issue by FireAstrox** [yeSpud/CS-372-Project#52]
ive created a couple of test videos, one used www.example.com and the other used https://www.youtube.com/watch?v=cen0rBKLuYE both displayed "No video supported with MIME type found." Is there a specific formatting for links or required links?

**Comment by yeSpud** [comment]
It should link to a video file such as https://archive.org/download/SteamboatWillie/Steamboat%20Willie.mp4

This is something that could be caught on our end with some URL validation on the backend and a note on the frontend however, so Ill get on this as soon as I can

**Comment by Alaskanyoda** [comment]
Here are some video links that should work for you:
https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2f/Making_snowman_in_Kõrvemaa%2C_Estonia_(January_2022).webm/Making_snowman_in_Kõrvemaa%2C_Estonia_(January_2022).webm.360p.webm](https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2f/Making_snowman_in_K%C3%B5rvemaa%2C_Estonia_(January_2022).webm/Making_snowman_in_K%C3%B5rvemaa%2C_Estonia_(January_2022).webm.360p.webm)

https://ia801300.us.archive.org/31/items/steamboat-willie_1928/steamboat-willie_1928.ia.mp4

https://upload.wikimedia.org/wikipedia/commons/transcoded/d/da/Paris_lockdown_-_Vimeo.webm/Paris_lockdown_-_Vimeo.webm.1080p.vp9.webm

**Comment by FireAstrox** [comment]
The first link in that link does not work @Alaskanyoda, it gives the same error

**Comment by yeSpud** [comment]
Yeah theres some weirdness going on with that first link - try https://upload.wikimedia.org/wikipedia/commons/transcoded/2/2f/Making_snowman_in_K%C3%B5rvemaa%2C_Estonia_(January_2022).webm/Making_snowman_in_K%C3%B5rvemaa%2C_Estonia_(January_2022).webm.360p.webm
